### ISSUE TITLE
Compile error when disabling OTA (NO_USE_OTA)

### ISSUE THREAD

**Issue by loebelch** [RalfJL/VE.Direct2MQTT#1]
When disabling OTA in config.h:
`#define NO_USE_OTA`

I got a compile error stating:
```
D:\development\arduino\sketches\VE.Direct2MQTT\VE.Direct2MQTT.ino: In function 'void setup()':
VE.Direct2MQTT:75:14: error: 'setClock' was not declared in this scope
     setClock();

```
When activating OTA compile is successful.

**Environment:** current master branch via Arduino IDE 1.8.13.

**Comment by RalfJL** [comment]
Moved setClock to vedirectWiFi. 
set Clock is also needed for SSL connection to MQTT so it needs to be done anyway
