### ISSUE TITLE
At least on VE ports you don't need the voltage divider.

### ISSUE THREAD

**Issue by rin67630** [RalfJL/VE.Direct2MQTT#10]
The 5V output of the Victron VE port is is so weak that it is easily clamped to 3,3 V by the ESP on board.

**Comment by RalfJL** [comment]
Actually some people say the ESP32 is even 5V tolerant.
But better safe than sorry.
Thanks for the information

**Comment by RalfJL** [comment]
Super,
thanks for checking. Never the less I will keep the documentation. Better safe than sorry
