### ISSUE TITLE
CANBUS Fork

### ISSUE THREAD

**Issue by gutowscr471** [RalfJL/VE.Direct2MQTT#13]
I've got he sijones fork of this running but I can't clearly see the pins from the CAN controller to the ESP32 and there is no mapping that I've found.  Do you have any more information on this?  Unfortunately there is no discussion or issues on the sijones fork of this.

**Comment by RalfJL** [comment]
Sorry,
currently I do not know much about CAN bus. So I can't help. I do see that the fork is just using the VE.Direct protocol from my sources. Everything else is pretty different.
