### ISSUE TITLE
Sporadic changes in which block of data is sent to MQTT broker

### ISSUE THREAD

**Issue by amygrooters** [RalfJL/VE.Direct2MQTT#14]
Thanks for all the time you put into this code and for making it available.  I'm trying to use it with a Smart Shunt which outputs a block of historical data parameters (H1-H12 and H15-H18) as well as a block of current data parameters (PID through MON).  

The problem I'm having is that I get sporadic differences in which block of data is sent to the MQTT broker. Sometimes it sends the historical data as well as the current data, sometimes it sends just the historical data, and sometimes it sends just the current data.  Sometimes it will send both for the first loop or two and then just send the historical data.  Based on the data coming through the serial monitor it appears that all of key/value pairs for all of the data is being received fine - it's just is inconsistent in terms of which block of data then gets sent (changes on restart).  I've tried messing around with the number of key/value pairs and the number of blocks in buffer but get the same problem. Have also tried on both the ESP32-WROOM-32 and the ESP32-WROOM-32D.

Any suggestions would be much appreciated.  Note - edited to add text files showing serial monitor debugging data

[smartshuntdata_1.txt](https://github.com/RalfJL/VE.Direct2MQTT/files/14575035/smartshuntdata_1.txt)
[smartshuntdata_2.txt](https://github.com/RalfJL/VE.Direct2MQTT/files/14575036/smartshuntdata_2.txt)
[smartshuntdata_3.txt](https://github.com/RalfJL/VE.Direct2MQTT/files/14575039/smartshuntdata_3.txt)

**Comment by errolt** [comment]
Hi @amygrooters 

It looks like the smart shunt sends 2 blocks of data every second. One with the current data, and one with the H values.

This confuses the code, as it is only expecting one block. Have you tried to set VE_WAIT_TIME = 0?

**Comment by amygrooters** [comment]
> Have you tried to set VE_WAIT_TIME = 0?

I haven't but will try it and report back.  Thanks!

**Comment by amygrooters** [comment]
> Have you tried to set VE_WAIT_TIME = 0?

That did it - am getting all of the parameters consistently now.   Thank you so much [errolt](https://github.com/errolt)!!
