### ISSUE TITLE
This is no issue, only a question!

### ISSUE THREAD

**Issue by gibetnicht** [RalfJL/VE.Direct2MQTT#3]
Is it possible to connect to a victron smart shunt and get the data to an esp32? 

I want to build a Home Assistant Server to collect these data by mqtt.

It would be fine to hear from you. My mailadress is womo4us@gmail.com.

Thanks and stay healthy.

**Comment by RalfJL** [comment]
Hi,
sorry for being late.
According to the specs the smart shunt is using VEDirect.
My program does not make any assumption on what device is sending the messages.
So yes, it should work. Interpretation is depending on the sending device itself.
E.g. the Solar charger is sending H20=<some value> and you will have to look up the documentation from Victron, what it means.
Please make sure to test it with a 5V setup first to avoid any damage to the ESP32 or the shunt. If you do not see any output you can test it with a direct 3.3V setup.

Ralf
