### ISSUE TITLE
The unit crashed after some times.

### ISSUE THREAD

**Issue by kdeparade** [RalfJL/VE.Direct2MQTT#8]
Your Code works well without changes . However, the ESP32 hangs up after a while and I have to reset it. Have you noticed anything like this?

**Comment by RalfJL** [comment]
Found some missing return statments which are causing crashes.
Can you please try again?
Thanks

**Comment by RalfJL** [comment]
Any news here?

**Comment by kdeparade** [comment]
Hallo und danke der Nachfrage.
Das Thema habe ich nicht weiter verfolgt.
Jetzt habe ich jedoch eine sehr komfortable Lösung in Youtube gefunden.
Funktioniert perfekt.
https://www.youtube.com/watch?v=4kO6WVnofig&list=PL5fIbcrWUO6LrBw7RqAgfYn69UcU73KtX&index=29&t=390s

Gruss
Kai-Uwe

Am Mi., 24. Apr. 2024 um 10:01 Uhr schrieb RalfJL ***@***.***

**Comment by RalfJL** [comment]
Cool Tasmota can now handle VE.Direct.
Tasmota is more and more the swiss army knife for IoT
Actually I should stop this project, as it is better replaced with Tasmota.
Thanks for the hint.
Ralf
