### ISSUE TITLE
#include <Preferences.h>

### ISSUE THREAD

**Issue by iukbox** [RalfJL/VE.Direct2MQTT#9]
Erster Fehler beim Kompilieren. Wo finde ich die Datei?

**Comment by RalfJL** [comment]
Preferences.h ist Teil der Library Preferences, die den Zugriff auf EEPROM regelt.
Bitte im IDE über Bibliotheksverwaltung nachinstallieren

**Comment by iukbox** [comment]
Danke

Der Code kann derzeit nur einen Victron ve.direct verwalten, richtig?

**Comment by RalfJL** [comment]
Hallo,
ja, aktuell ist gedacht pro VE.Direkt Gerät ein ESP32. Ich habe zwar 2 Geräte, aber die stehen weit auseinander, so dass ich nicht anders testen kann.

Mit den Libraries ist das immer so eine Sache, da sich verwendete Libraries auf andere Libraries abstützen können.
In der Regel hilft es, den Code zu kompilieren und dann bekommt man heraus, welche Header fehlen. Und die sucht man dann in der Bibliotheksverwaltung. Manchmal passiert es sogar, dass der Code compilierte, dann aber ein Update einer Library eine andere zusätzlich will.
Hier sind die wichtigsten:
PubSubClient für die MQTT Anbindung
Preferences
StringSplitter
Und dann kommen noch die Libraries, die nur bei gesetzten ifdef's ziehen, wie z.B.
DallasTemperature
